apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-71mi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yzsu-tenant/quarkus/devfile-sample-code-with-quarkus-71mi@sha256:dc7e69c93de49acafe066dc41587e7fbe21e5d600b89f53f3c5be070b77008c3
        name: my-java-quarkus
        resources: {}
status: {}
